### ISSUE TITLE
ERROR: Subject doesnt have a Fat Image , Please verified input volume name

### ISSUE THREAD

**Issue by ziling-wh** [reuter-lab/FatSegNet#2]

**Comment by santiestrada32** [comment]
Hello, they could be two issues
1) Mounting files to the docker image: For the tool to access your data the files have to be mount to the docker image as follows
nvidia-docker run --rm --name fatsegnet -u $(id -u) -v ../my_dataset/:/tool/Data -v ../my_dataset_output/:/tool/Output  adipose_tool:v1 [Arguments]
2) the name of the water and fat images are case sensitive so please make sure the name of the water and fat image is like: FatImaging_F.nii.gz for fat and  FatImaging_W.nii.gz, if you use the default configuration. If you want to use different name use the  -fat , -water flag as explain in the read me file. 
# Change name of water and fat images to search
nvidia-docker run [Options]  adipose_tool:v1  -fat fat_image.nii.gz -water water_image.nii.gz -loc.

This a real case example :

nvidia-docker run -it --rm  --name fatsegnet -u $(id -u) -v /home/estradae/Downloads/Rotterdam/:/tool/Data  -v /home/estradae/Downloads/Rotterdam/:/tool/Output  adipose_tool:v1 -f participants.csv -gpu_id 0 -outp all_models -fat ab_fat.nii.gz -water ab_water.nii.gz
