### ISSUE TITLE
Cannot find my file

### ISSUE THREAD

**Issue by TongKang1** [reuter-lab/FatSegNet#6]
**ERROR: Subject doesnt have a Fat Image named FatImaging_F.nii.gz,**

I already put the correct file into correct path, why this program cannot found?
By the way, I run your code under win10 2004 environment with docker.

![image](https://user-images.githubusercontent.com/35797048/88558147-c1ca0680-d05d-11ea-982d-5e6f8c3abeb6.png)
![image](https://user-images.githubusercontent.com/35797048/88558314-ec1bc400-d05d-11ea-94e7-411783b08136.png)
![image](https://user-images.githubusercontent.com/35797048/88558840-aca1a780-d05e-11ea-891d-b4e5eae84643.png)

**Comment by santiestrada32** [comment]
Please mount the local paths to your docker container as follows
docker run -it --rm --name fatsegnet -u $(id -u) -v ../my_dataset/:/tool/Data -v ../my_dataset_output/:/tool/Output  adipose_tool:cpu_v1 [Arguments]

docker contatiner dont have access to your volumes if you dont mount them
