### ISSUE TITLE
No partipant file found, please provide one the input data folder

### ISSUE THREAD

**Issue by golansapir** [reuter-lab/FatSegNet#7]
Hey,
I'm stuck trying to run.
It can't find my participants csv file even though it's in the correct folder.

`$ sudo docker run adipose_tool:cpu_v1 --file participants.csv
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
No partipant file found, please provide one the input data folder
`
![Screenshot from 2020-08-17 14-41-39](https://user-images.githubusercontent.com/50543970/90392559-c64f7100-e097-11ea-9585-858537bda64e.png)

**Comment by santiestrada32** [comment]
hello
please mount the input folders to the docker image
 as follows

docker run -it --rm --name fatsegnet -u $(id -u) -v ../my_dataset/:/tool/Data -v ../my_dataset_output/:/tool/Output  adipose_tool:cpu_v1 [Arguments]

docker container dont have access to your data if you dont mount the corresponding file

**Comment by golansapir** [comment]
Thank you for your fast replay,
I've tried it and still no success...


` sudo docker run --rm --name fatsegnet -u $(id -u) -v '/home/sapir/FatSegNet/tool/Data/my_dataset' -v '/home/sapir/FatSegNet/tool/Output' adipose_tool:cpu_v1

[sudo] password for sapir: 

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
No partipant file found, please provide one the input data folder
`

**Comment by golansapir** [comment]
I think I don't understand this part-
 ../my_dataset/:/tool/Data 
and what I need to type in it

**Comment by santiestrada32** [comment]
you have to type the location of your local folder and mount it to the tool folder

as follows

sudo docker run --rm --name fatsegnet -u $(id -u) -v /home/sapir/FatSegNet/tool/Data/my_dataset:/tool/Data -v /home/sapir/FatSegNet/tool/Output:/tool/Output adipose_tool:cpu_v1

please check https://docs.docker.com/storage/volumes/ for a more comprehensive explanation of how docker mounts data

**Comment by santiestrada32** [comment]
A docker container doesnt have access to the system files so volumes has to be mounted. For our tool is necessary to mount the main data directory my_dataset to /tool/Data and the desire local output folder to /tool/Output. The output folder is where all pipeline output are going to be store (the input and output folder can be the same). We additionally recommend to use the following docker flags:

    --rm : Automatically clean up the container and remove the file system when the container exits
    --user , -u : Username or UID (format: <name|uid>[:<group|gid>])
    --name : Assign a name to the container
    --volume , -v: Bind mount a volume

**Comment by golansapir** [comment]
Thank you,
I believe it's running now..

**Comment by golansapir** [comment]
So I have the results but I suspect something went wrong..
I'm using InPahse OutPhase images to create the Fat and Water images using the well-known calculation -
W_Image=0.5*(IP+OP)
F_Image=0.5*(IP-OP)

Do you think it's fine to use these as my Fat and Water images?

**Comment by golansapir** [comment]
![QC_2](https://user-images.githubusercontent.com/50543970/90404785-872b1b00-e0ab-11ea-8208-15ad270b5f94.png)
 as you can see, here's the QC

**Comment by santiestrada32** [comment]
which resolution are your images? by the picture you sent, i will recommend running the adipose pipeline only in the axial plane. 

# run only the segmentation models on the axial 
nvidia-docker run [Options]  adipose_tool:v1  -axial

**Comment by golansapir** [comment]
The scan is 320/320/44 but as you requested I rescaled it to 256 224 72
I will try the axial plane and will update
TNX!!

**Comment by santiestrada32** [comment]
your resulting image looks quite noisy, so probably you have to change the method of how you do your interpolation. you can pass your 320/320/44 image to the pipeline and include the followings
flags
-axial -order 1

--order,-order : Interpolation order (0=nearest,1=linear(default),2=quadratic,3=cubic),the tool standardizes the input resolutions to [2mm,2mm,5mm]; if the axial flag is selected only the axial plane is sample.

**Comment by golansapir** [comment]
Hey again,
So we ran the analysis, once with all planes and once with the -axial plane only.
When analyzing the axial plane only - all of the results are with "High VAT to SAT ratio" flag.
When analyzing in all planes - 60% have "High VAT to SAT ratio" flag and 40% have "SAT increase over the threshold"

What would you suggest?

**Comment by santiestrada32** [comment]
without seeing the images is hard for me to say, these flags are just warnings doesn't mean the segmentation failed. You should check the status of the segmentation by opening the images.
