### ISSUE TITLE
normalization for intensity range

### ISSUE THREAD

**Issue by stebo85** [reuter-lab/FatSegNet#9]
Dear FatSegNet developers,

I am trying to apply FatSegNet to Dixon data acquired with a similar protocol to your training data, but running the network on the raw intensity range leads to sub-optimal results:
![image](https://user-images.githubusercontent.com/4021595/102044592-e3683680-3e22-11eb-8e4a-37a3d995d895.png)
![image](https://user-images.githubusercontent.com/4021595/102044681-17435c00-3e23-11eb-8389-19c8df2d4133.png)

I tried to manually find an intensity shift where the predictions don't fail and it seems that this works better:
![image](https://user-images.githubusercontent.com/4021595/102044695-1f9b9700-3e23-11eb-96d7-f372f9a02bad.png)

![image](https://user-images.githubusercontent.com/4021595/102044703-21fdf100-3e23-11eb-828c-73e6d1d5256a.png)

What normalization technique did you use and what was your intensity range of the training data of the models provided?

**Comment by santiestrada32** [comment]
For this version, we didn't do any normalization technique. For future releases, we intend to normalize the input as we saw this has limited the implementation of our method in other datasets.
